CREATOR:
  name: "GUB, Göteborgs universitetsbibliotek, Digitala tjänster"
  sigel: "Gdig"

ARCHIVIST:
  name: "UUB, Uppsala universitetsbibliotek"
  sigel: "U"

COPYRIGHT_STATUS:
  true: "copyrighted"
  false: "pd"

PUBLICATION_STATUS:
  true: "unpublished"
  false: "unpublished"
