---

### USER ROLES DEFINITION
### Create a new role by adding another hash with a unique name of the role as well as a list of rights. Unassignable states that the role cannot be assigned to users.
### Available rights are: 'view_users', 'manage_users', 'view_tree', 'manage_tree', 'manage_tree_root'
user_roles:
  -
    name: ADMIN
    rights:
      - view_users
      - manage_users
      - view_tree
      - manage_tree
      - manage_tree_root
      - manage_jobs
  -
    name: GUEST
    rights:
      - view_tree
    unassignable: true
  -
    name: OPERATOR
    rights:
      - view_tree
      - manage_tree
      - manage_jobs
  -
    name: API_KEY
    rights:
      - view_tree
      - manage_tree
      - manage_tree_root
      - manage_jobs
      - manage_users
      - view_users
    unassignable: true

# Flags for using external authentication source
external_auth: true

# Adapter for file management
file_adapter: dfile

# List of available sources
sources:
  -
    name: libris
    label: Libris
    class_name: Libris
  -
    name: dc
    label: DC
    class_name: DublinCore
  -
    name: dcxml
    label: DC-XML
    class_name: DublinCoreXML
  -
    name: document
    label: Document
    class_name: Document
  -
    name: letter
    label: Letter
    class_name: Letter

# List of available events (used for job activity entries)
events:
  -
    name: QUARANTINE
  -
    name: UNQUARANTINE
  -
    name: CREATE
  -
    name: UPDATE
  -
    name: CHANGE_STATUS
  -
    name: DELETE
  -
    name: FLOW_STEP
  -
    name: RESTART

# List of available statuses
statuses:
  -
    name: waiting_for_digitizing
    next_status: digitizing
    state: START
  -
    name: digitizing
    previous_status: waiting_for_digitizing
    next_status: post_processing
    state: PROCESS
  -
    name: post_processing
    next_status: quality_control
    state: PROCESS
  -
    name: post_processing_user_input
    previous_status: post_processing
    next_status: post_processing
    state: ACTION
  -
    name: quality_control
    next_status: waiting_for_package_metadata_import
    state: ACTION
  -
    name: waiting_for_package_metadata_import
    next_status: package_metadata_import
    state: PROCESS
  -
    name: package_metadata_import
    next_status: waiting_for_mets_control
    state: PROCESS
  -
    name: waiting_for_mets_control
    next_status: mets_control
    state: PROCESS
  -
    name: mets_control
    next_status: done
    state: PROCESS
  -
    name: done
    next_status:
    state: FINISH

# List of processes and their calling status
processes:
  -
    code: PACKAGE_METADATA_IMPORT
    status: waiting_for_package_metadata_import
  -
    code: CREATE_METS_PACKAGE
    status: waiting_for_mets_control

# Defines the format of the package name
package_name: GUB%07d

# Defines the layout and contents of job work order pdf (used in app/models/pdf_helper.rb)
pdf_settings:
  operators: "[ ] Maria     [ ] Grim     [ ] Ingela"
  equipments: "[ ] Robot    [ ] Zeutschel    [ ] Canon "
