---
# CONTAINS SYSTEM DATA, DO NOT CHANGE PER APPLICATION INSTANCE

user_roles:
- name: ADMIN
  rights:
  - view_users
  - manage_users
  - view_tree
  - manage_tree
  - manage_tree_root
  - manage_jobs
  - manage_statistics
- name: GUEST
  rights:
  - view_tree
  unassignable: true
- name: API_KEY
  rights:
  - view_tree
  - manage_tree
  - manage_tree_root
  - manage_jobs
  - manage_users
  - view_users
  - manage_statistics
  unassignable: true
publication_types:
- MANUSCRIPT
- WIKIPEDIA
- GUPEA
- LIBRIS
- DCAT_LIBRIS_ID
- DCAT_HOLDING_ID
sources:
- name: libris
  label: Libris
  class_name: Libris
- name: dc
  label: DC
  class_name: DublinCore
- name: document
  label: Document
  class_name: Document
  hidden: true
- name: letter
  label: Letter
  class_name: Letter
  hidden: true
events:
- name: QUARANTINE
- name: UNQUARANTINE
- name: CREATE
- name: UPDATE
- name: CHANGE_STATUS
- name: DELETE
- name: FLOW_STEP
- name: RESTART
- name: STATUS
- name: STARTED
- name: FINISHED
- name: SKIPPED
processes:
- code: CONFIRMATION
  state: ACTION
  required_params:
  - manual
- code: QUALITY_CONTROL
  state: ACTION
  required_params:
  - pdf_file_path
  - manual
- code: ASSIGN_METADATA
  state: ACTION
  required_params:
    - manual
    - images_folder_path
    - save
    - source
    - filetype
- code: ASSIGN_FLOW_PARAMETERS
  state: ACTION
  required_params:
    - manual
    - save
- code: IMPORT_PACKAGE_METADATA
  state: PROCESS
- code: CREATE_METS_PACKAGE
  state: PROCESS
- code: WAIT_FOR_FILES
  state: WAITFOR
  required_params:
    - folder_path
    - filetype
    - count
- code: WAIT_FOR_FILE
  state: WAITFOR
  required_params:
    - file_path
- code: COPY_FOLDER
  state: PROCESS
  required_params:
    - source_folder_path
    - destination_folder_path
- code: MOVE_FOLDER
  state: PROCESS
  required_params:
    - source_folder_path
    - destination_folder_path
- code: COPY_FILE
  state: PROCESS
  required_params:
    - source_file_path
    - destination_file_path
- code: COLLECT_JOB_METADATA
  state: PROCESS
  required_params:
    - folder_path
    - filetype
- code: CREATE_FORMAT
  state: PROCESS
  required_params:
    - source_folder_path
    - destination_folder_path
    - to_filetype
    - format
- code: DELETE_JOB_FILES
  state: PROCESS
  required_params:
    - job_parent_path
- code: COMBINE_PDF_FILES
  state: PROCESS
  required_params:
    - source_folder_path
    - destination_file_path
- code: CREATE_GUPEA_PACKAGE
  state: PROCESS
  required_params:
    - gupea_collection
    - gupea_folder_path
    - pdf_file_path
- code: CREATE_METS_FILE
  state: PROCESS
  required_params:
    - job_folder_path
    - mets_file_path
    - formats_required
    - files_required
    - creator_name
    - creator_sigel
- code: CHANGE_PACKAGE_LOCATION
  state: PROCESS
  required_params:
    - new_package_location
- code: IMPORT_JOBS
  state: PROCESS
  required_params:
    - file_path
    - treenode_id
    - copyright
    - flow_id
    - source_name
- code: CREATE_LIBRIS_ITEM
  state: PROCESS
  required_params:
    - libris_id
    - url
queue_manager:
  pid_file_location: "/tmp/dflow_queue_manager_pid"
